### ISSUE TITLE
Hollow Knight modding (on linux) breaks controller support

### ISSUE THREAD

**Issue by embeddedpenguin** [hk-modding/api#107]
I've got an issue where simply enabling mods at all (without turning any mods on) breaks controller support. I'm using a PS4 controller through steam. The controller touchpad works, but nothing else works.

**Comment by embeddedpenguin** [comment]
Using scarab with v1.5 fixes this for whatever reason. I have no clue where in the stack the problem actually exists so I'm just going to leave this open until it gets eyes.

**Comment by fifty-six** [comment]
This was fixed in ab723014146cdfac5706a8c9eba8a27eb6793cf8 if updating fixed it.
