### ISSUE TITLE
When is the next release planned ?

### ISSUE THREAD

**Issue by PrashantMohta** [hk-modding/api#110]
There are major fixes that have been merged into master that, IMO, warrant a release.

 is there a reason for not creating a new release ?

**Comment by fifty-six** [comment]
There's still a PR open and I wanted to change something before releasing and I'm at home for a week due to spring break. If you feel it's very necessary I can merge the PR and release I guess.

**Comment by PrashantMohta** [comment]
Tbh, I mostly only care about https://github.com/hk-modding/api/commit/669b7f58cab50371bcfeb95571fb8beb048c1bc3 because HKMP api exists and I don't want all mods wanting to work with it to have a hard dependency on HKMP.

Personally, IDM waiting for a week, but this and the pause menu fix are critical fixes that IMO should be released asap.

**Comment by fifty-six** [comment]
I also dislike releasing super often so I was waiting till I had merged all the PRs and had cleaned up what I wanted to. Given that this is entirely on free time and I haven't had motivation nor free time it has taken me a bit to get to things. If someone had mentioned that 669b7f5 was actually affecting a bunch of people then I would've just released when I merged that. If you can't wait a week you can just emit a derived type at runtime, bit of a pain though. If it's super important I can get someone else to test what I wanted to change; it's pretty small anyways.

**Comment by flibber-hk** [comment]
> If someone had mentioned that https://github.com/hk-modding/api/commit/669b7f58cab50371bcfeb95571fb8beb048c1bc3 was actually affecting a bunch of people then I would've just released when I merged that.

Just to clarify, the HKMP API wasn't released until last week so it wasn't an issue until then (and given that it's not been around for super long it's fine to wait a week or two IMO).

**Comment by PrashantMohta** [comment]
I agree with @flibber-hk , a week or two is not an issue as far as there's a plan to release somewhat soon.

**Comment by SFGrenade** [comment]
> I also dislike releasing super often so I was waiting till I had merged all the PRs and had cleaned up what I wanted to. Given that this is entirely on free time and I haven't had motivation nor free time it has taken me a bit to get to things. If someone had mentioned that [669b7f5](https://github.com/hk-modding/api/commit/669b7f58cab50371bcfeb95571fb8beb048c1bc3) was actually affecting a bunch of people then I would've just released when I merged that. If you can't wait a week you can just emit a derived type at runtime, bit of a pain though. If it's super important I can get someone else to test what I wanted to change; it's pretty small anyways.

i'm open to test if you want
