### ISSUE TITLE
IMod instead of Mod

### ISSUE THREAD

**Issue by Ruttie2006** [hk-modding/api#136]
ModLoader.cs has the following:
https://github.com/hk-modding/api/blob/21ba19b0e70d1a0b703eea9cb874f22a6d35cc7d/Assembly-CSharp/ModLoader.cs#L169
Why does this check for `typeof(Mod)` instead of seeing if it has the `IMod` interface?
This way, instead of having custom `Mod` classes that implement `IMod`, every custom mod class has to derive from `Mod`, which is quite limiting imo.

**Comment by fifty-six** [comment]
`IMod` is largely just legacy, we rely on it being `Mod` in order to add members when wanted as well as for other implementation details.
