### ISSUE TITLE
this loader broke my controller

### ISSUE THREAD

**Issue by atesin** [hk-modding/api#140]
hi....  i have a generic directinput usb gamepad, i have to use xbox 360 control emulator (x360ce) to be able to use in many games, with this, my controller works flawlessly

... except with hollow knight that functions intermitently... i spent a year without being able to play HK because of this, until some time ago when i discovered **Button Prompt Switcher** ( https://steamcommunity.com/sharedfiles/filedetails/?id=2525497719 ), that says it *fixes intermitent control*

ok, so i installed the switcher (by replacing a modified Assembly-CSharp.dll file) and effectively it fixed my intermitent control, so i could came back to play HK! xD

.....  until i installed scarab mod manager (what uses this lib) ... so my mods worked, but my old controller problem returns .... so i realized the mod overwrote my Assembly-CSharp.dll file again

i don't know what Button Prompt Switcher does to fix the intermitent controller...  but seem that thing is not applied in kh-modding Assembly-CSharp.dll file  ...  so i cant have the better of both worlds, i have to choose between play HK plain without mods, or install mods but not being able to play :(

could you please also apply intermitent control fix yo your dll file so i could play with mods? ..  thanks

p.s.: i have HK GOG version (i.e. no steam)

**Comment by TheMulhima** [comment]
you can install [this](https://discord.com/channels/879125729936298015/879130542501658624/1007029075782664293) mod which does the same thing. For the settings, it's the same as the steam post but instead of specifying them in command line, it's set in the modmenu.

**Comment by fifty-six** [comment]
Given what Mulhima has posted, this should be a non-issue now.

**Comment by atesin** [comment]
> you can install [this](https://cdn.discordapp.com/attachments/879130542501658624/1007029074906054779/Button_Prompt_Switcher.dl) mod which does the same thing. For the settings, it's the same as the steam post but instead of specifying them in command line, it's set in the modmenu.

(the link is broken)

"button prompt switcher" mod is not installed trought scarab mod manager, but directly...  and uses a different modification of same library (Assembly-CSharp.dll)...  so both mods overwites the same file and are incompatible each other

i am begging for scarab mod manager make the same controller fix as button prompt switcher, to being able to install mods and also fix controller issues at same time.... currently scarab mod manager has a broken controller, same as original lib in which is based i guess

**Comment by TheMulhima** [comment]
yea mb the link was broken heres the correct link for the [download](https://cdn.discordapp.com/attachments/879130542501658624/1007029074906054779/Button_Prompt_Switcher.dll). If you don't want to download it directly I am planning to add it to scarab soon (probably in the weekend)

**Comment by atesin** [comment]
thanks for the link....  but in my starting post i mention i DO HAD installed button prompt switcher....

the problem is with BPS scarab doesnt work...  and with scarab alone, the gamepad is broken either...  so you can't have both mods coexist because they overwrite the same file each other

my question is to scarab apply the same fix than BPS, so we can have scarab with a fixed gamepad... because by installing BPS we lose access to our mods

**Comment by TheMulhima** [comment]
A modding API compatible version is available on modlinks now. If you install Button Prompt Switcher from scarab/any other modinstaller, the fixes to controller should work while being able to download other mods. If it doesn't work as intended please report it in the [modding server](https://discord.gg/VDsg3HmWuB)

**Comment by atesin** [comment]
NO WAY ....  thank you..  thank you so much

however when installed it gives me errors....  after digging a little (and after some game restarts) i realizet it was due misinformed dependencies...   these are

- HKMirror
- Satchel

once they are installed, i could play HK+mods without controller issues....  i already notified BPS mod developer here = https://github.com/TheMulhima/Button-Prompt-Switcher/issues/1
