### ISSUE TITLE
[Feature] Collapsible mod list

### ISSUE THREAD

**Issue by olee** [hk-modding/api#145]
Hi, I'm trying to play modded HK on the Steam Deck, which is working great so far.
However, because of the smaller screen the list of installed mods when in the pause screen overlays a lot of the other mod UIs like benchwarp.
It would be great if there were some option to collapse the mod list so it only shows some info text to expand that list again in the top left.

I would like to even contribute this myself, however I was not able to find out where this mod list is implemented (if this is even the correct repository for this)

**Comment by fifty-six** [comment]
It's implemented at [`ModVersionDraw`](https://github.com/hk-modding/api/blob/master/Assembly-CSharp/ModVersionDraw.cs) and the calls using it in [`ModLoader`](https://github.com/hk-modding/api/blob/master/Assembly-CSharp/ModLoader.cs) fwiw.

**Comment by BadMagic100** [comment]
HideModList on your favorite mod installer implements this, along with provisions that make it so that SRC verifiers can be certain it's not being used to sneak banned mods into speedruns

**Comment by olee** [comment]
Ok... somehow I wasn't able to find that mod at all before because in all the posts people always complained to questions about the poster "wanting to hide mods for fake speedruns" etc.
