### ISSUE TITLE
HK Modding API doesn't seem to work with the latest game update on June 28 2021

### ISSUE THREAD

**Issue by Joshaze** [hk-modding/api#61]
White window with a progress bar and a red exclamation mark [ ! ] pops up momentarily then closes and the game never starts.

<img width="475" alt="SplashScreenRedExclaim" src="https://user-images.githubusercontent.com/63926402/125453155-eef3d42e-78f7-4a68-9721-1eea5d5544a5.png">

This occurs with or without any DLLs inside the Mods folder.

Assembly-CSharp files were copied to the correct location, overriding the existing DLL.

Fresh installation of the game and ran verify files.

**Comment by SFGrenade** [comment]
Have you tried using the newest modding api on a game version that isn't 1.4.3.2 or not use the one on the installer on a game version that isn't the new 1.5 update?

**Comment by fifty-six** [comment]
There isn't a release out for the latest version, you can grab an artifact off CI and that should work.

**Comment by Ruttie2006** [comment]
https://docs.google.com/document/d/1NmYCR8diRropqFDm9-n1aR0_XuQSHRdfxgsY4WrVmSs/edit#heading=h.a8snmuu0ih96 ?

**Comment by mandar1jn** [comment]
you are probably using the 1.4 version. Download [this](https://github.com/hk-modding/api/suites/3169965491/artifacts/73004714) instead for 1.5

**Comment by fifty-six** [comment]
Gonna close this, can be re-opened if needed but this seems to be a 1.4 API install on 1.5
