### ISSUE TITLE
Mod menu seems weird when leaving via esc

### ISSUE THREAD

**Issue by flibber-hk** [hk-modding/api#67]
When I open the mod menu (on 1.5, build 28), toggle an IToggleable mod and then close the menu by pressing Esc, it saves the state of the mod menu (so the mod menu says the mod is off) but doesn't do what it's supposed to (so the mod is still enabled). I'm not sure if this is a bug but it feels like you would want to make it so when the menu is closed, the actual settings match the settings on the menu.

ETA: when I open the mod menu again, the button state matches how I left it (so the IToggleable mod is marked as disabled, which is what I set it to, even though the mod is actually still enabled)

(I have the latest QoL installed, just in case that matters)

**Comment by mandar1jn** [comment]
Is this still a thing?

**Comment by flibber-hk** [comment]
In the interest of making a suggestion, I'd propose making it so that clicking the button calls the delegate immediately rather than waiting for the player to click back.

**Comment by fifty-six** [comment]
Closed by #83.
