### ISSUE TITLE
Load order can mess up mods

### ISSUE THREAD

**Issue by mandar1jn** [hk-modding/api#72]
As you probably know I'm working on Fyremoth. With the mod installer for 1.5 got released I decided to update to the latest modding API version and ran into an issue. This issue turned out to be SFCore loading after Fyremoth loads. This is why I'd like to request either the librar attribute to be brought back or to run some kind of dependency check when loading mods.

**Comment by fifty-six** [comment]
Do you have a repro case or can I have the dll? The resolve event *should* be handling that

**Comment by mandar1jn** [comment]
@fifty-six I can send you the dll in dm (on discord) in a few hours. Also: can it be that that does not work since they are in the same parent folder but different sub folders?

**Comment by fifty-six** [comment]
Without code for reproducing the error or a dll, I'm going to close as can't reproduce in a bit

**Comment by mandar1jn** [comment]
Oh. Sorry. I totally forgot I had this issue open

**Comment by fifty-six** [comment]
Error was from having multiple dlls with different versions.
