### ISSUE TITLE
controller button bindings dieing on UIManager Recreation

### ISSUE THREAD

**Issue by TheMulhima** [hk-modding/api#84]
if you open save then close it (causing UIManager to be destroyed and recreated), the controller button bindings kinda just die. (Note that on first start up, it works properly)

in the picture, there are supposed to be 3 keybinds, but there's only 1 and it doesn't look how its supposed to.

[Error in modlog can be found here](https://pastebin.com/dPNqYpyk)

[How it was implemented](https://github.com/Dastan21/HollowKnight.PantheonsHitCounter/blob/a2934ec1c3b629aca2625c4c6d633a7f1d78011a/PantheonsHitCounter/ModMenu.cs#L128-L171) and [download for mod](https://github.com/Dastan21/HollowKnight.PantheonsHitCounter/releases/download/v1.0.1/PantheonsHitCounter.zip) can be found by clicking on links
<img width="960" alt="Hollow_Knight_19_30_38_402" src="https://user-images.githubusercontent.com/81007262/141809215-c15db07d-1bbd-48f0-b401-082e3f1f94d2.png">

**Comment by PrashantMohta** [comment]
Current running theory is the internal reference to input handler is no longer valid when doing a s&q, I have not had more time to look into it further yet, adding a try-catch around the controller binding allows it to work for now, while keeping it compatible with whatever the future fix would be.
